apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: prod

namespace: clouds-api-prod

bases:
  - ../../base

resources:
  - namespace.yaml

images:
- name: quay.io/gfontana/clouds-api
  newName: image-registry.openshift-image-registry.svc:5000/cicd/clouds-api
  newTag: v1.0
